#!/usr/bin/python3
"""Unittest for max_integer([..])
"""
import unittest
max_integer = __import__('6-max_integer').max_integer


class TestMaxInteger(unittest.TestCase):

    def test_ordered_list(self):
        self.assertEqual(max_integer([1, 2, 3, 4]), 4)

    def test_unordered_list(self):
        self.assertEqual(max_integer([1, 3, 4, 2]), 4)

    def test_empty_list(self):
        self.assertIsNone(max_integer([]))

    def test_single_element(self):
        self.assertEqual(max_integer([10]), 10)

    def test_negative_values(self):
        self.assertEqual(max_integer([-5, -2, -9]), -2)

    def test_floats(self):
        self.assertEqual(max_integer([1.5, 2.3, 0.7]), 2.3)

    def test_mixed_int_float(self):
        self.assertEqual(max_integer([1, 2.5, 3]), 3)

